<?php


add_action('init', 'js_inc_function');
add_theme_support( 'post-formats', array( 'link', 'gallery', 'video' , 'audio') );
add_theme_support( 'automatic-feed-links' );
add_theme_support( 'post-thumbnails' ); // this enable thumbnails and stuffs
add_image_size( 'blog', 580, 280, true );
add_image_size( 'related', 146,83, true );
add_image_size( 'gallery', 95,95, true );
add_image_size( 'widget',85,55, true );
add_image_size( 'sinbgleport', 610,'', true );
add_image_size( 'port2',230,150, true );
add_image_size( 'port3', 310,230, true );
add_image_size( 'port4', 230,133, true );
add_image_size( 'advertise', 160,160, true );
/*-----------------------------------------------------------------------------------*/
// Options Framework
/*-----------------------------------------------------------------------------------*/


// Paths to admin functions
define('MY_TEXTDOMAIN', 'wp-rockPalace');
load_theme_textdomain( 'wp-rockPalace', get_template_directory() . '/languages' );
define('ADMIN_PATH', get_stylesheet_directory() . '/admin/');
define('BOX_PATH', get_stylesheet_directory() . '/includes/boxes/');
define('ADMIN_DIR', get_template_directory_uri() . '/admin/');
define('LAYOUT_PATH', ADMIN_PATH . '/layouts/');

// You can mess with these 2 if you wish.
$themedata = wp_get_theme(get_stylesheet_directory() . '/style.css');
define('THEMENAME', $themedata['Name']);
define('OPTIONS', 'of_options'); // Name of the database row where your options are stored

if (is_admin() && isset($_GET['activated'] ) && $pagenow == "themes.php" ) {
	//Call action that sets

	add_action('admin_head','of_option_setup');

}


function of_option_setup()	{



	if (!get_option('of_options')){

		$data = 'YToxMzg6e3M6MTQ6InNob3dyZXNwb25zaXZlIjtzOjE6IjEiO3M6MTM6InNob3dhZHZlcnRpc2UiO3M6MToiMSI7czoxNToiaW5mb3RleHRfc3RhdHVzIjtzOjE6IjEiO3M6MTA6ImJveF9zdGF0dXMiO3M6MToiMSI7czoxODoicmFjZW50X3N0YXR1c19wb3J0IjtzOjE6IjEiO3M6MTg6ImhvbWVfcmVjZW50X251bWJlciI7czoxOiI5IjtzOjI2OiJob21lX3JlY2VudF9udW1iZXJfZGlzcGxheSI7czoxOiIzIjtzOjEzOiJyYWNlbnRfc3RhdHVzIjtzOjE6IjEiO3M6MzE6ImhvbWVfcmVjZW50X251bWJlcl9kaXNwbGF5X3Bvc3QiO3M6MToiMyI7czoyMzoiaG9tZV9yZWNlbnRfbnVtYmVyX3Bvc3QiO3M6MToiNyI7czoxNjoiaG9lbXJlY2VudGRlc2lnbiI7czoxOiIxIjtzOjg6ImluZm90ZXh0IjtzOjY0OiJXZWxjb21lIHRvIDxzcGFuPlJPQ0sgUEFMQUNFPC9zcGFuPiAtIEEgcm9ja2FibGUgV29yZHByZXNzIFRoZW1lIjtzOjE5OiJxdW90ZV9ib3R0b21fYm9yZGVyIjtzOjE6IjEiO3M6MTA6ImJveDFfdGl0bGUiO3M6MTc6IlJFU1BPTlNJVkUgREVTSUdOIjtzOjEwOiJib3gxX2ltYWdlIjtzOjgyOiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9yZXNwb25zaXZlSWNvbjIucG5nIjtzOjk6ImJveDFfbGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjE2OiJib3gxX2Rlc2NyaXB0aW9uIjtzOjEwNToiPHN0cm9uZz5Eb25lYyBwZWRlPC9zdHJvbmc+IGp1c3RvLCBmcmluZ2lsbGEgdmVsLCBhbCwgdnVscHV0YXRlIA0KZWdldCwgYXJjdS4gSW4gZW5pbSBqdXN0bywgbG9yZW0gaXBzdW0uIjtzOjEwOiJib3gxX2NvbG9yIjtzOjc6IiMxZTFlMjAiO3M6MTA6ImJveDJfdGl0bGUiO3M6MTI6IjI0LzcgU1VQUE9SVCI7czoxMDoiYm94Ml9pbWFnZSI7czo3OToiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvc3VwcG9ydEljb24xLnBuZyI7czo5OiJib3gyX2xpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxNjoiYm94Ml9kZXNjcmlwdGlvbiI7czoxMDU6IjxzdHJvbmc+RG9uZWMgcGVkZTwvc3Ryb25nPiBqdXN0bywgZnJpbmdpbGxhIHZlbCwgYWwsIHZ1bHB1dGF0ZSANCmVnZXQsIGFyY3UuIEluIGVuaW0ganVzdG8sIGxvcmVtIGlwc3VtLiI7czoxMDoiYm94Ml9jb2xvciI7czo3OiIjY2MzMzMzIjtzOjEwOiJib3gzX3RpdGxlIjtzOjEzOiJNQU5ZIFNFVFRJTkdTIjtzOjEwOiJib3gzX2ltYWdlIjtzOjgwOiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9zZXR0aW5nc0ljb24xLnBuZyI7czo5OiJib3gzX2xpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxNjoiYm94M19kZXNjcmlwdGlvbiI7czoxMDU6IjxzdHJvbmc+RG9uZWMgcGVkZTwvc3Ryb25nPiBqdXN0bywgZnJpbmdpbGxhIHZlbCwgYWwsIHZ1bHB1dGF0ZSANCmVnZXQsIGFyY3UuIEluIGVuaW0ganVzdG8sIGxvcmVtIGlwc3VtLiI7czoxMDoiYm94M19jb2xvciI7czo3OiIjMWUxZTIwIjtzOjE0OiJhZHZlcnRpc2VpbWFnZSI7YTo5OntpOjE7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6OToiU3BvbnNvciAxIjtzOjM6InVybCI7czo3NToiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3BvbnNvcjEucG5nIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7fWk6MjthOjQ6e3M6NToib3JkZXIiO3M6MToiMiI7czo1OiJ0aXRsZSI7czo5OiJTcG9uc29yIDIiO3M6MzoidXJsIjtzOjc1OiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9zcG9uc29yMi5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTozO2E6NDp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgMyI7czozOiJ1cmwiO3M6NzU6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3IzLnBuZyI7czo0OiJsaW5rIjtzOjI0OiJodHRwOi8vcHJlbWl1bWNvZGluZy5jb20iO31pOjQ7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjQiO3M6NToidGl0bGUiO3M6OToiU3BvbnNvciA0IjtzOjM6InVybCI7czo3NToiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3BvbnNvcjQucG5nIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7fWk6NTthOjQ6e3M6NToib3JkZXIiO3M6MToiNSI7czo1OiJ0aXRsZSI7czo5OiJTcG9uc29yIDUiO3M6MzoidXJsIjtzOjc1OiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9zcG9uc29yNi5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTo2O2E6NDp7czo1OiJvcmRlciI7czoxOiI2IjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgNiI7czozOiJ1cmwiO3M6NzU6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3I5LnBuZyI7czo0OiJsaW5rIjtzOjI0OiJodHRwOi8vcHJlbWl1bWNvZGluZy5jb20iO31pOjc7YTo0OntzOjU6Im9yZGVyIjtzOjE6IjciO3M6NToidGl0bGUiO3M6OToiU3BvbnNvciA3IjtzOjM6InVybCI7czo3NzoiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3BvbnNvci0xMC5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTo4O2E6NDp7czo1OiJvcmRlciI7czoxOiI4IjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgOCI7czozOiJ1cmwiO3M6NzY6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3I1MS5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9aTo5O2E6NDp7czo1OiJvcmRlciI7czoxOiI5IjtzOjU6InRpdGxlIjtzOjk6IlNwb25zb3IgOSI7czozOiJ1cmwiO3M6Nzk6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzA5L3Nwb25zb3JMb2dvNy5wbmciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjt9fXM6NDoibG9nbyI7czo3MjoiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvbG9nbzEucG5nIjtzOjc6ImZhdmljb24iO3M6NzQ6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL2Zhdmljb24ucG5nIjtzOjE2OiJnb29nbGVfYW5hbHl0aWNzIjtzOjQ0OiI8c2NyaXB0IHR5cGU9XCJ0ZXh0L2phdmFzY3JpcHRcIj4NCjwvc2NyaXB0PiI7czo5OiJtYWluQ29sb3IiO3M6NzoiI2NjMzMzMyI7czo4OiJib3hDb2xvciI7czo3OiIjMWUxZTIwIjtzOjE1OiJTaGFkb3dDb2xvckZvbnQiO3M6NzoiIzAwMDAwMCI7czoyMzoiU2hhZG93T3BhY2l0dHlDb2xvckZvbnQiO3M6MzoiMC4yIjtzOjIxOiJib2R5X2JhY2tncm91bmRfY29sb3IiO3M6NzoiI2ZhZmFmYSI7czoxNjoiYmFja2dyb3VuZF9pbWFnZSI7czoxOiIxIjtzOjc6ImJvZHlfYmciO3M6ODM6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdGhlbWVzL3JvY2tQYWxhY2UvaW1hZ2VzL2JnL2JnMTYucG5nIjtzOjE4OiJib2R5X2JnX3Byb3BlcnRpZXMiO3M6MTA6InJlcGVhdCAwIDAiO3M6MjM6ImJhY2tncm91bmRfaW1hZ2VfaGVhZGVyIjtzOjE6IjEiO3M6MjM6ImhlYWRlcl9iYWNrZ3JvdW5kX2NvbG9yIjtzOjc6IiMxZTFlMjAiO3M6OToiaGVhZGVyX2JnIjtzOjkwOiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3RoZW1lcy9yb2NrUGFsYWNlL2ltYWdlcy9iZy1mb290ZXIvYmcwMi5wbmciO3M6MjA6ImhlYWRlcl9iZ19wcm9wZXJ0aWVzIjtzOjEwOiJyZXBlYXQgMCAwIjtzOjEyOiJjdXN0b21fc3R5bGUiO3M6MDoiIjtzOjk6Imlvc3NsaWRlciI7YTo0OntpOjE7YTo1OntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6NTI6Ik1VU0lDIEVWRU5UIFdJVEggREogU1RBUlRJTkcgQVQgMjAuMDAgT04gQVVHVVNUIDE1VEgiO3M6MzoidXJsIjtzOjExMToiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvcGhvdG9kdW5lLTE3NDg4OS1yb2NraW5nLXRoZS1uaWdodC1hd2F5LXMtYncuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NjgwOiJXZWxjb21lIHRvIG91ciBtYWpvciBldmVudCB0aGF0IHdpbGwgdGFrZSBwbGFjZSBpbiBvdXIgYmFyLCBiZXNpZGVzIG91ciBTdG9yZS4gVGhlcmUgd2lsbCBiZSBzZXZlcmFsIHJlbm93bmVkIHBlcmZvcm1lcyB0aGF0IHdpbGwgdGFrZSBjYXJlIG9mIHlvdXIgZWFycywgc29tZSBhcmUgbGlzdGVkIGJlbG93Og0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KT0hOIERPRTwvaDM+IC0gTWl4IEFtYXppbmcgRWxla3RybyBTb3VuZA0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5KQU5FIERPRTwvaDM+IC0gQmVzdCBESiBpbiBUb3duDQo8YnI+PGJyPg0KPGgzIHN0eWxlID0gXCJjb2xvcjojZmZmO21hcmdpbjowO1wiPkNBVEhFUklORSBET0U8L2gzPiAtIFdvcmtpbmcgdXAgdGhlIEJlYXQNCjxicj48YnI+DQo8aDMgc3R5bGUgPSBcImNvbG9yOiNmZmY7bWFyZ2luOjA7XCI+R0xKSVZFQzwvaDM+IC0gV29ya2luZyBkb3duIHRoZSBCZWF0DQo8YnI+PGJyPg0KRXZlbnQgd2lsbCBzdGFydCBhdCA4cG0uIElmIHlvdSBoYXZlIGFueSBxdWVzdGlvbnMgYWJvdXQgdGhlIEV2ZW50IG9yIHRoaXMgVGVtcGxhdGUsIHlvdSBjYW4gYXNrIHVzIGF0IDxzdHJvbmc+c3VwcG9ydEBwcmVtaXVtY29kaW5nLmNvbTwvc3Ryb25nPiA6KSI7fWk6MjthOjU6e3M6NToib3JkZXIiO3M6MToiMiI7czo1OiJ0aXRsZSI7czozOToiTElWRSBDT05DRVJUIFdJVEggQSBSRU5PV05FRCBST0NLIEdST1VQIjtzOjM6InVybCI7czoxMDk6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3Bob3RvZHVuZS0yMTcwODE5LWRydW0td2l0aC1kcnVtc3RpY2stcy1idy5qcGciO3M6NDoibGluayI7czowOiIiO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjA6IiI7fWk6MzthOjU6e3M6NToib3JkZXIiO3M6MToiMyI7czo1OiJ0aXRsZSI7czo0NjoiTklHSFQgQ0xVQiBPUEVOSU5HIFRPTklHSFQgV0lUSCBTUEVDSUFMIEdVRVNUUyI7czozOiJ1cmwiO3M6OTQ6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3Bob3RvZHVuZS0xMTg1NzY0LXJvY2stcy1idy5qcGciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czo2ODA6IldlbGNvbWUgdG8gb3VyIG1ham9yIGV2ZW50IHRoYXQgd2lsbCB0YWtlIHBsYWNlIGluIG91ciBiYXIsIGJlc2lkZXMgb3VyIFN0b3JlLiBUaGVyZSB3aWxsIGJlIHNldmVyYWwgcmVub3duZWQgcGVyZm9ybWVzIHRoYXQgd2lsbCB0YWtlIGNhcmUgb2YgeW91ciBlYXJzLCBzb21lIGFyZSBsaXN0ZWQgYmVsb3c6DQo8YnI+PGJyPg0KPGgzIHN0eWxlID0gXCJjb2xvcjojZmZmO21hcmdpbjowO1wiPkpPSE4gRE9FPC9oMz4gLSBNaXggQW1hemluZyBFbGVrdHJvIFNvdW5kDQo8YnI+PGJyPg0KPGgzIHN0eWxlID0gXCJjb2xvcjojZmZmO21hcmdpbjowO1wiPkpBTkUgRE9FPC9oMz4gLSBCZXN0IERKIGluIFRvd24NCjxicj48YnI+DQo8aDMgc3R5bGUgPSBcImNvbG9yOiNmZmY7bWFyZ2luOjA7XCI+Q0FUSEVSSU5FIERPRTwvaDM+IC0gV29ya2luZyB1cCB0aGUgQmVhdA0KPGJyPjxicj4NCjxoMyBzdHlsZSA9IFwiY29sb3I6I2ZmZjttYXJnaW46MDtcIj5HTEpJVkVDPC9oMz4gLSBXb3JraW5nIGRvd24gdGhlIEJlYXQNCjxicj48YnI+DQpFdmVudCB3aWxsIHN0YXJ0IGF0IDhwbS4gSWYgeW91IGhhdmUgYW55IHF1ZXN0aW9ucyBhYm91dCB0aGUgRXZlbnQgb3IgdGhpcyBUZW1wbGF0ZSwgeW91IGNhbiBhc2sgdXMgYXQgPHN0cm9uZz5zdXBwb3J0QHByZW1pdW1jb2RpbmcuY29tPC9zdHJvbmc+IDopIjt9aTo0O2E6NTp7czo1OiJvcmRlciI7czoxOiI0IjtzOjU6InRpdGxlIjtzOjUzOiJMSVZFIEdVSVRBUiBDT05DRVJUIFdJVEggU0VWRVJBTCBXRUxMIEtOT1dOIE1VU0lDSUFOUyI7czozOiJ1cmwiO3M6ODI6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL2d1aXRhci1jb25jZXJ0MS5qcGciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czowOiIiO319czoxMToiZGVtb19zbGlkZXIiO2E6NDp7aToxO2E6ODp7czo1OiJvcmRlciI7czoxOiIxIjtzOjU6InRpdGxlIjtzOjU6Ik1hc2tzIjtzOjM6InVybCI7czo3ODoiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMTEvZW1wdHlIb2xkZXIucG5nIjtzOjU6InZpZGVvIjtzOjA6IiI7czozOiJ0b3AiO3M6MjoiMjUiO3M6NDoibGVmdCI7czoyOiI1NyI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6MTc4ODoiPGRpdiBjbGFzcz1cImNhcHRpb25Cb3hcIiBzdHlsZT1cImhlaWdodDogMjM1cHg7IG1hcmdpbi1sZWZ0OjQwcHg7IHotaW5kZXg6MTI7XCI+DQo8aDEgY2xhc3M9XCJ1bmRlcmxpbmVcIiBzdHlsZT1cInBhZGRpbmc6IDE1cHggMjVweCAxNXB4IDBweDsgZm9udC1zaXplOiAyNnB4ICFpbXBvcnRhbnQ7XCI+TFAgQ09MTEVDVElPTjwvaDE+DQo8dWwgY2xhc3M9XCJxdW90ZVwiIHN0eWxlPVwicGFkZGluZy1yaWdodDogMjBweDtcIj4NCgk8bGkgY2xhc3M9XCJsZWZ0XCI+WW91IGNhbiBhZGQgPHN0cm9uZz51bmlxdWUgPC9zdHJvbmc+IGltYWdlczwvbGk+DQoJPGxpIGNsYXNzPVwicmlnaHRcIj50byBlYWNoIHNsaWRlIGFuZCBtYWtlIHRoZW0gPHNwYW4gc3R5bGU9XCJmb250LXdlaWdodDogYm9sZDtcIj5kaXN0aW5jdC48L3NwYW4+PC9saT4NCgk8bGkgY2xhc3M9XCJsZWZ0XCI+R2V0IHRoZSBjb21wbGV0ZSA8c3BhbiBzdHlsZT1cImZvbnQtd2VpZ2h0OiBib2xkO1wiPmZyZWVkb208L3NwYW4+IG9mIHlvdXIgZGVzaWduLjwvbGk+DQoJPGxpIGNsYXNzPVwicmlnaHRcIj5BIGNyZWF0aXZlIGFwcHJvYWNoIHRvIDxzdHJvbmc+d2ViIGRlc2lnbi48L3N0cm9uZz48L2xpPg0KPC91bD4NCjx1bD4NCgk8bGkgY2xhc3M9XCJidXR0b25cIj48YSBocmVmPVwiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tXCI+UkVBRCBNT1JFPC9hPjwvbGk+DQo8L3VsPg0KPC9kaXY+DQoNCjx1bD4NCg0KDQo8bGkgY2xhc3M9XCJ0b3AxXCI+DQo8YSBocmVmID1cImh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vcHJvZHVjdC9iZWF1dGlmdWwtd2hpdGUtcGVhcmxzL1wiPg0KPGltZyBzdHlsZSA9IFwibWFyZ2luOi0xMTBweCAwcHggMCAtNjAwcHg7XCIgc3JjPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9zbGlkZXNob3ctaW1hZ2UtNC5wbmcNClwiIGFsdD1cImltYWdlXCIvPjwvYT48L2xpPg0KDQo8bGkgY2xhc3M9XCJ0b3AyXCI+DQo8YSBocmVmID1cImh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vcHJvZHVjdC9hLXN0eWxpc2gtY2Fybml2YWwtbWFzay9cIj4NCjxpbWcgc3R5bGUgPSBcIm1hcmdpbjotMTEwcHggMHB4IDAgLTM2MHB4O1wiIHNyYz1cImh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvc2xpZGVzaG93LWltYWdlLTMucG5nDQpcIiBhbHQ9XCJpbWFnZVwiLz48L2E+PC9saT4NCg0KPGxpIGNsYXNzPVwidG9wM1wiPg0KPGEgaHJlZiA9XCJodHRwOi8vbXVzaWNhLnByZW1pdW1jb2RpbmcuY29tL3Byb2R1Y3QvdmlvbGluby1jb25jZXJ0by9cIj4NCjxpbWcgc3R5bGUgPSBcIm1hcmdpbjoxMzBweCAwcHggMCAtNjAwcHg7XCIgc3JjPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9zbGlkZXNob3ctaW1hZ2UtMi5wbmcNClwiIGFsdD1cImltYWdlXCIvPjwvYT48L2xpPg0KDQo8bGkgY2xhc3M9XCJ0b3A0XCI+DQo8YSBocmVmID1cImh0dHA6Ly9tdXNpY2EucHJlbWl1bWNvZGluZy5jb20vcHJvZHVjdC9zdHJhbmdlLXRvLXlvdXItZWFycy9cIj4NCjxpbWcgc3R5bGUgPSBcIm1hcmdpbjoxMzBweCAwcHggMCAtMzYwcHg7XCIgc3JjPVwiaHR0cDovL211c2ljYS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9zbGlkZXNob3ctaW1hZ2UtMS5wbmcNClwiIGFsdD1cImltYWdlXCIvPjwvYT48L2xpPg0KDQo8L3VsPg0KDQogIjt9aToyO2E6ODp7czo1OiJvcmRlciI7czoxOiIyIjtzOjU6InRpdGxlIjtzOjU6IlZpZGVvIjtzOjM6InVybCI7czowOiIiO3M6NToidmlkZW8iO3M6Mzg6Imh0dHA6Ly9wbGF5ZXIudmltZW8uY29tL3ZpZGVvLzI0NDU2Nzg3IjtzOjM6InRvcCI7czoxOiI2IjtzOjQ6ImxlZnQiO3M6NDoiNzkuMSI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6Njc5OiI8ZGl2IGNsYXNzPVwiY2FwdGlvbkJveFwiIHN0eWxlPVwiaGVpZ2h0OiA0NDBweDsgd2lkdGg6MjAwcHg7XCI+DQo8aDEgY2xhc3M9XCJ1bmRlcmxpbmVcIiBzdHlsZT1cInBhZGRpbmc6IDE1cHggMjVweCAxNXB4IDBweDsgZm9udC1zaXplOiAyNnB4ICFpbXBvcnRhbnQ7XCI+VklERU9TPC9oMT4NCjx1bCBjbGFzcz1cInF1b3RlXCIgc3R5bGU9XCJwYWRkaW5nLXJpZ2h0OiAyMHB4O1wiPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5Zb3UgY2FuIGFkZCB2aWRlb3MNCglhbmQgYWRkIGRlc2NyaXB0aW9uDQoJVGVsbCB5b3VyIHZpc2l0b3JzLg0KCXdoYXQgaXRcXFwncyBhYm91dC4NCiAgICAgICAgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVlciBhZGlwaXNjaW5nIGVsaXQsIHNlZCBkaWFtIG5vbnVtbXkgbmliaCBldWlzbW9kIHRpbmNpZHVudCB1dCBsYW9yZWV0IGRvbG9yZSBtYWduYSBhbGlxdWFtIGVyYXQgdm9sdXRwYXQuICBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dWVyIGFkaXBpc2NpbmcgZWxpdC4gTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQ8L3N0cm9uZz48L2xpPg0KPC91bD4NCg0KCTxsaSBjbGFzcz1cImJ1dHRvblwiPjxhIGhyZWY9XCJodHRwOi8vcHJlbWl1bWNvZGluZy5jb21cIj5SRUFEIE1PUkU8L2E+PC9saT4NCg0KPC9kaXY+Ijt9aTozO2E6ODp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjU6IklwYWRzIjtzOjM6InVybCI7czo3ODoiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMTEvZW1wdHlIb2xkZXIucG5nIjtzOjU6InZpZGVvIjtzOjA6IiI7czozOiJ0b3AiO3M6MjoiMjQiO3M6NDoibGVmdCI7czoyOiI2MCI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6MTQ0NDoiPHVsPg0KPGxpIGNsYXNzPVwidG9wMlwiIHN0eWxlPVwiei1pbmRleDo5O1wiPg0KPGEgaHJlZiA9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tXCI+DQo8aW1nIGFsdD1cImltYWdlXCIgc3R5bGUgPSBcIm1hcmdpbjoyMHB4IDBweCAwIC02ODVweDtcIiBzcmM9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzEwL2lwaG9uZS5wbmcNClwiLz48L2E+PC9saT4NCg0KDQo8bGkgY2xhc3M9XCJ0b3AxXCIgc3R5bGU9XCJ6LWluZGV4Ojg7XCI+DQo8YSBocmVmID1cImh0dHA6Ly9kYWVkcmEucHJlbWl1bWNvZGluZy5jb21cIj4NCjxpbWcgYWx0PVwiaW1hZ2VcIiBzdHlsZSA9IFwibWFyZ2luOi02M3B4IDBweCAwIC02MjBweDtcIiBzcmM9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzEwL2xjZG1vbml0b3IucG5nDQpcIi8+PC9hPjwvbGk+DQoNCjxsaSBjbGFzcz1cInRvcDNcIiBzdHlsZT1cInotaW5kZXg6MTA7XCI+DQo8YSBocmVmID1cImh0dHA6Ly9kYWVkcmEucHJlbWl1bWNvZGluZy5jb21cIj4NCjxpbWcgYWx0PVwiaW1hZ2VcIiBzdHlsZSA9IFwibWFyZ2luOjEwNnB4IDBweCAwIC0zMzBweDtcIiBzcmM9XCJodHRwOi8vZGFlZHJhLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzEwL2lwYWQucG5nDQpcIi8+PC9hPjwvbGk+DQoNCjwvdWw+DQoNCg0KDQoNCg0KPGRpdiBjbGFzcz1cImNhcHRpb25Cb3hcIiBzdHlsZT1cImhlaWdodDogMjM1cHg7XCI+DQo8aDEgY2xhc3M9XCJ1bmRlcmxpbmVcIiBzdHlsZT1cInBhZGRpbmc6IDE1cHggMjVweCAxNXB4IDBweDsgZm9udC1zaXplOiAyNnB4ICFpbXBvcnRhbnQ7XCI+VU5MSU1JVEVEIElNQUdFUzwvaDE+DQo8dWwgY2xhc3M9XCJxdW90ZVwiIHN0eWxlPVwicGFkZGluZy1yaWdodDogMjBweDtcIj4NCgk8bGkgY2xhc3M9XCJsZWZ0XCI+WW91IGNhbiBhZGQgPHN0cm9uZz51bmlxdWUgPC9zdHJvbmc+IHdpZGUgaW1hZ2VzPC9saT4NCgk8bGkgY2xhc3M9XCJyaWdodFwiPnZpZGVvcyBhbmQgZXh0cmEgaW1hZ2VzIDxzcGFuIHN0eWxlPVwiZm9udC13ZWlnaHQ6IGJvbGQ7XCI+dG8gc2xpZGVyLjwvc3Bhbj48L2xpPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5HZXQgdGhlIGNvbXBsZXRlIDxzcGFuIHN0eWxlPVwiZm9udC13ZWlnaHQ6IGJvbGQ7XCI+ZnJlZWRvbTwvc3Bhbj4gb2YgeW91ciBkZXNpZ24uPC9saT4NCgk8bGkgY2xhc3M9XCJyaWdodFwiPkEgY3JlYXRpdmUgYXBwcm9hY2ggdG8gPHN0cm9uZz53ZWIgZGVzaWduLjwvc3Ryb25nPjwvbGk+DQo8L3VsPg0KPHVsPg0KCTxsaSBjbGFzcz1cImJ1dHRvblwiPjxhIGhyZWY9XCJodHRwOi8vcHJlbWl1bWNvZGluZy5jb21cIj5SRUFEIE1PUkU8L2E+PC9saT4NCjwvdWw+DQo8L2Rpdj4NCiI7fWk6NDthOjg6e3M6NToib3JkZXIiO3M6MToiNCI7czo1OiJ0aXRsZSI7czo1OiJJbWFnZSI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEyLzExL3JhaWx3YXkuanBnIjtzOjU6InZpZGVvIjtzOjA6IiI7czozOiJ0b3AiO3M6MjoiMjUiO3M6NDoibGVmdCI7czoyOiIyNSI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6NjkyOiI8ZGl2IGNsYXNzPVwiY2FwdGlvbkJveFwiIHN0eWxlPVwiaGVpZ2h0OiAyMzVweDtcIj4NCjxoMSBjbGFzcz1cInVuZGVybGluZVwiIHN0eWxlPVwicGFkZGluZzogMTVweCAyNXB4IDE1cHggMHB4OyBmb250LXNpemU6IDI2cHggIWltcG9ydGFudDtcIj5VTkxJTUlURUQgSU1BR0VTPC9oMT4NCjx1bCBjbGFzcz1cInF1b3RlXCIgc3R5bGU9XCJwYWRkaW5nLXJpZ2h0OiAyMHB4O1wiPg0KCTxsaSBjbGFzcz1cImxlZnRcIj5Zb3UgY2FuIGFkZCA8c3Ryb25nPnVuaXF1ZSA8L3N0cm9uZz4gd2lkZSBpbWFnZXM8L2xpPg0KCTxsaSBjbGFzcz1cInJpZ2h0XCI+dmlkZW9zIGFuZCBleHRyYSBpbWFnZXMgPHNwYW4gc3R5bGU9XCJmb250LXdlaWdodDogYm9sZDtcIj50byBzbGlkZXIuPC9zcGFuPjwvbGk+DQoJPGxpIGNsYXNzPVwibGVmdFwiPkdldCB0aGUgY29tcGxldGUgPHNwYW4gc3R5bGU9XCJmb250LXdlaWdodDogYm9sZDtcIj5mcmVlZG9tPC9zcGFuPiBvZiB5b3VyIGRlc2lnbi48L2xpPg0KCTxsaSBjbGFzcz1cInJpZ2h0XCI+QSBjcmVhdGl2ZSBhcHByb2FjaCB0byA8c3Ryb25nPndlYiBkZXNpZ24uPC9zdHJvbmc+PC9saT4NCjwvdWw+DQo8dWw+DQoJPGxpIGNsYXNzPVwiYnV0dG9uXCI+PGEgaHJlZj1cImh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbVwiPlJFQUQgTU9SRTwvYT48L2xpPg0KPC91bD4NCjwvZGl2PiI7fX1zOjExOiJuaXZvX3NsaWRlciI7YTozOntpOjE7YTo1OntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6NTI6Ik1VU0lDIEVWRU5UIFdJVEggREogU1RBUlRJTkcgQVQgMjAuMDAgT04gQVVHVVNUIDE1VEgiO3M6MzoidXJsIjtzOjExNjoiaHR0cDovL3JvY2twYWxhY2UucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTMvMDEvcGhvdG9kdW5lLTE3NDg4OS1yb2NraW5nLXRoZS1uaWdodC1hd2F5LXMtYnctbml2by5qcGciO3M6NDoibGluayI7czoyNDoiaHR0cDovL3ByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czo1MjoiTVVTSUMgRVZFTlQgV0lUSCBESiBTVEFSVElORyBBVCAyMC4wMCBPTiBBVUdVU1QgMTVUSCI7fWk6MjthOjU6e3M6NToib3JkZXIiO3M6MToiMiI7czo1OiJ0aXRsZSI7czo1MzoiTElWRSBHVUlUQVIgQ09OQ0VSVCBXSVRIIFNFVkVSQUwgV0VMTCBLTk9XTiBNVVNJQ0lBTlMiO3M6MzoidXJsIjtzOjgyOiJodHRwOi8vcm9ja3BhbGFjZS5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMy8wMS9ndWl0YXItY29uY2VydDIuanBnIjtzOjQ6ImxpbmsiO3M6MjQ6Imh0dHA6Ly9wcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6NTM6IkxJVkUgR1VJVEFSIENPTkNFUlQgV0lUSCBTRVZFUkFMIFdFTEwgS05PV04gTVVTSUNJQU5TIjt9aTozO2E6NTp7czo1OiJvcmRlciI7czoxOiIzIjtzOjU6InRpdGxlIjtzOjQ2OiJOSUdIVCBDTFVCIE9QRU5JTkcgVE9OSUdIVCBXSVRIIFNQRUNJQUwgR1VFU1RTIjtzOjM6InVybCI7czoxMTQ6Imh0dHA6Ly9yb2NrcGFsYWNlLnByZW1pdW1jb2RpbmcuY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDEzLzAxL3Bob3RvZHVuZS0yMTcwODE5LWRydW0td2l0aC1kcnVtc3RpY2stcy1idy1uaXZvLmpwZyI7czo0OiJsaW5rIjtzOjA6IiI7czoxMToiZGVzY3JpcHRpb24iO3M6NDY6Ik5JR0hUIENMVUIgT1BFTklORyBUT05JR0hUIFdJVEggU1BFQ0lBTCBHVUVTVFMiO319czoxNDoic2xpZGVyX29wYWNpdHkiO3M6MzoiMC45IjtzOjg6ImFuaXNwZWVkIjtzOjM6IjgwMCI7czo5OiJwYXVzZXRpbWUiO3M6NToiMjAwMDAiO3M6MjU6InNsaWRlcl9mb250U2l6ZV9jb2xvck5pdm8iO2E6Mjp7czo0OiJzaXplIjtzOjQ6IjI0cHgiO3M6NToiY29sb3IiO3M6NzoiI2ZmZmZmZiI7fXM6MjA6InNsaWRlcl9iYWNrQ29sb3JOaXZvIjtzOjc6IiNjYzMzMzMiO3M6MjI6InNsaWRlcl9ib3JkZXJDb2xvck5pdm8iO3M6NzoiI2NjMzMzMyI7czo2OiJlZmZlY3QiO3M6NjoicmFuZG9tIjtzOjY6InNsaWNlcyI7czoyOiIxNSI7czo3OiJib3hjb2xzIjtzOjE6IjgiO3M6NzoiYm94cm93cyI7czoxOiI0IjtzOjk6ImJvZHlfZm9udCI7YTozOntzOjQ6InNpemUiO3M6NDoiMTNweCI7czo1OiJjb2xvciI7czo3OiIjMmEyYjJjIjtzOjQ6ImZhY2UiO3M6MTQ6IkhlbHZldGljYSBOZXVlIjt9czoxMjoiaGVhZGluZ19mb250IjthOjI6e3M6NDoiZmFjZSI7czo2OiJPc3dhbGQiO3M6NToic3R5bGUiO3M6Njoibm9ybWFsIjt9czo5OiJtZW51X2ZvbnQiO3M6MTQ6IkhlbHZldGljYSBOZXVlIjtzOjE0OiJib2R5X2JveF9jb2xlciI7czo3OiIjZmZmZmZmIjtzOjE1OiJib2R5X2xpbmtfY29sZXIiO3M6NzoiIzJhMmIyYyI7czoxNToiaGVhZGluZ19mb250X2gxIjthOjI6e3M6NDoic2l6ZSI7czo0OiIyOHB4IjtzOjU6ImNvbG9yIjtzOjc6IiMyYTJiMmMiO31zOjE1OiJoZWFkaW5nX2ZvbnRfaDIiO2E6Mjp7czo0OiJzaXplIjtzOjQ6IjI0cHgiO3M6NToiY29sb3IiO3M6NzoiIzJhMmIyYyI7fXM6MTU6ImhlYWRpbmdfZm9udF9oMyI7YToyOntzOjQ6InNpemUiO3M6NDoiMjBweCI7czo1OiJjb2xvciI7czo3OiIjMmEyYjJjIjt9czoxNToiaGVhZGluZ19mb250X2g0IjthOjI6e3M6NDoic2l6ZSI7czo0OiIxOHB4IjtzOjU6ImNvbG9yIjtzOjc6IiMyYTJiMmMiO31zOjE1OiJoZWFkaW5nX2ZvbnRfaDUiO2E6Mjp7czo0OiJzaXplIjtzOjQ6IjE3cHgiO3M6NToiY29sb3IiO3M6NzoiIzJhMmIyYyI7fXM6MTU6ImhlYWRpbmdfZm9udF9oNiI7YToyOntzOjQ6InNpemUiO3M6NDoiMTZweCI7czo1OiJjb2xvciI7czo3OiIjMmEyYjJjIjt9czo0OiJ0ZWFtIjthOjY6e2k6MTthOjExOntzOjU6Im9yZGVyIjtzOjE6IjEiO3M6NToidGl0bGUiO3M6ODoiSmFuZSBEb2UiO3M6NDoicm9sZSI7czoxOToiUHJlc2lkZW50ICYgRm91bmRlciI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjEuanBnIjtzOjQ6Imljb24iO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvZm91bmRlclRlYW0ucG5nIjtzOjc6InR3aXR0ZXIiO3M6MzI6Imh0dHA6Ly90d2l0dGVyLmNvbS9wcmVtaXVtY29kaW5nIjtzOjg6ImZhY2Vib29rIjtzOjM2OiJodHRwOi8vd3d3LmZhY2Vib29rLmNvbS9HRmxhc2hEZXNpZ24iO3M6NToidmltZW8iO3M6MTY6Imh0dHA6Ly92aW1lby5jb20iO3M6NzoiZHJpYmJsZSI7czoyNzoiaHR0cDovL2RyaWJiYmxlLmNvbS9nbGppdmVjIjtzOjQ6Im1haWwiO3M6MjI6ImluZm9AcHJlbWl1bWNvZGluZy5jb20iO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjI3MToiPGI+TG9yZW0gaXBzdW08L2I+IGRvbG9yIHNpdCBhbWV0IGRhcyBjb25zZSANCm5pYmggZXVpc21vZG9zIHRpbmNpZHVudCB1dCBsYW9yZWUgY29uc2UNCmVzdCBhdC4gTnVsbGEgdml0YWUgPGI+ZWxpdCBsaWJlcm88L2I+LCBhIHBoYSBzaXQgYW0NCnRldHVlciBhZGlwaXNjaW5nIGVsaXQuIE51bGxhIHZpdGFlIGVsaXQgbGVybywgDQphIHBoYXJldHJhLiA8Yj5Mb3JlbSBpcHN1bTwvYj4gY3RldHVlciBhZGlwaXNjaW5nLiANCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LiI7fWk6MjthOjExOntzOjU6Im9yZGVyIjtzOjE6IjIiO3M6NToidGl0bGUiO3M6ODoiSm9obiBEb2UiO3M6NDoicm9sZSI7czoxMzoiV2ViIERldmVsb3BlciI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjIucG5nIjtzOjQ6Imljb24iO3M6Nzk6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvd2ViRGV2ZWxvcGVySWNvbi5wbmciO3M6NzoidHdpdHRlciI7czozMjoiaHR0cDovL3R3aXR0ZXIuY29tL3ByZW1pdW1jb2RpbmciO3M6ODoiZmFjZWJvb2siO3M6MzY6Imh0dHA6Ly93d3cuZmFjZWJvb2suY29tL0dGbGFzaERlc2lnbiI7czo1OiJ2aW1lbyI7czowOiIiO3M6NzoiZHJpYmJsZSI7czoyNzoiaHR0cDovL2RyaWJiYmxlLmNvbS9nbGppdmVjIjtzOjQ6Im1haWwiO3M6MjI6ImluZm9AcHJlbWl1bWNvZGluZy5jb20iO3M6MTE6ImRlc2NyaXB0aW9uIjtzOjI3MToiPGI+TG9yZW0gaXBzdW08L2I+IGRvbG9yIHNpdCBhbWV0IGRhcyBjb25zZSANCm5pYmggZXVpc21vZG9zIHRpbmNpZHVudCB1dCBsYW9yZWUgY29uc2UNCmVzdCBhdC4gTnVsbGEgdml0YWUgPGI+ZWxpdCBsaWJlcm88L2I+LCBhIHBoYSBzaXQgYW0NCnRldHVlciBhZGlwaXNjaW5nIGVsaXQuIE51bGxhIHZpdGFlIGVsaXQgbGVybywgDQphIHBoYXJldHJhLiA8Yj5Mb3JlbSBpcHN1bTwvYj4gY3RldHVlciBhZGlwaXNjaW5nLiANCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LiI7fWk6MzthOjExOntzOjU6Im9yZGVyIjtzOjE6IjMiO3M6NToidGl0bGUiO3M6MTM6Ikpvc2VwaGluZSBEb2UiO3M6NDoicm9sZSI7czoxNjoiQ3VzdG9tZXIgU2VydmljZSI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjMucG5nIjtzOjQ6Imljb24iO3M6Nzg6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvc3VwcG9ydFRlYW1JY29uLnBuZyI7czo3OiJ0d2l0dGVyIjtzOjMyOiJodHRwOi8vdHdpdHRlci5jb20vcHJlbWl1bWNvZGluZyI7czo4OiJmYWNlYm9vayI7czozNjoiaHR0cDovL3d3dy5mYWNlYm9vay5jb20vR0ZsYXNoRGVzaWduIjtzOjU6InZpbWVvIjtzOjA6IiI7czo3OiJkcmliYmxlIjtzOjA6IiI7czo0OiJtYWlsIjtzOjIyOiJpbmZvQHByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czoyNzE6IjxiPkxvcmVtIGlwc3VtPC9iPiBkb2xvciBzaXQgYW1ldCBkYXMgY29uc2UgDQpuaWJoIGV1aXNtb2RvcyB0aW5jaWR1bnQgdXQgbGFvcmVlIGNvbnNlDQplc3QgYXQuIE51bGxhIHZpdGFlIDxiPmVsaXQgbGliZXJvPC9iPiwgYSBwaGEgc2l0IGFtDQp0ZXR1ZXIgYWRpcGlzY2luZyBlbGl0LiBOdWxsYSB2aXRhZSBlbGl0IGxlcm8sIA0KYSBwaGFyZXRyYS4gPGI+TG9yZW0gaXBzdW08L2I+IGN0ZXR1ZXIgYWRpcGlzY2luZy4gDQpMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldC4iO31pOjQ7YToxMTp7czo1OiJvcmRlciI7czoxOiI0IjtzOjU6InRpdGxlIjtzOjY6IkRhbWllbiI7czo0OiJyb2xlIjtzOjk6IlBIUCBDb2RlciI7czozOiJ1cmwiO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvdGVhbU1lbWJlcjQucG5nIjtzOjQ6Imljb24iO3M6NzQ6Imh0dHA6Ly9tZXJjb3IucHJlbWl1bWNvZGluZy5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMTIvMDkvcGhwVGVhbUljb24ucG5nIjtzOjc6InR3aXR0ZXIiO3M6MzI6Imh0dHA6Ly90d2l0dGVyLmNvbS9wcmVtaXVtY29kaW5nIjtzOjg6ImZhY2Vib29rIjtzOjM2OiJodHRwOi8vd3d3LmZhY2Vib29rLmNvbS9HRmxhc2hEZXNpZ24iO3M6NToidmltZW8iO3M6MDoiIjtzOjc6ImRyaWJibGUiO3M6Mjc6Imh0dHA6Ly9kcmliYmJsZS5jb20vZ2xqaXZlYyI7czo0OiJtYWlsIjtzOjIyOiJpbmZvQHByZW1pdW1jb2RpbmcuY29tIjtzOjExOiJkZXNjcmlwdGlvbiI7czoyNzE6IjxiPkxvcmVtIGlwc3VtPC9iPiBkb2xvciBzaXQgYW1ldCBkYXMgY29uc2UgDQpuaWJoIGV1aXNtb2RvcyB0aW5jaWR1bnQgdXQgbGFvcmVlIGNvbnNlDQplc3QgYXQuIE51bGxhIHZpdGFlIDxiPmVsaXQgbGliZXJvPC9iPiwgYSBwaGEgc2l0IGFtDQp0ZXR1ZXIgYWRpcGlzY2luZyBlbGl0LiBOdWxsYSB2aXRhZSBlbGl0IGxlcm8sIA0KYSBwaGFyZXRyYS4gPGI+TG9yZW0gaXBzdW08L2I+IGN0ZXR1ZXIgYWRpcGlzY2luZy4gDQpMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldC4iO31pOjU7YToxMTp7czo1OiJvcmRlciI7czoxOiI1IjtzOjU6InRpdGxlIjtzOjEzOiJDaHJpc3RpbmEgRG9lIjtzOjQ6InJvbGUiO3M6OToiTWFya2V0ZWVyIjtzOjM6InVybCI7czo3NDoiaHR0cDovL21lcmNvci5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS90ZWFtTWVtYmVyNS5wbmciO3M6NDoiaWNvbiI7czo4MDoiaHR0cDovL21lcmNvci5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9tYXJrZXRpbmdUZWFtSWNvbi5wbmciO3M6NzoidHdpdHRlciI7czozMjoiaHR0cDovL3R3aXR0ZXIuY29tL3ByZW1pdW1jb2RpbmciO3M6ODoiZmFjZWJvb2siO3M6MzY6Imh0dHA6Ly93d3cuZmFjZWJvb2suY29tL0dGbGFzaERlc2lnbiI7czo1OiJ2aW1lbyI7czowOiIiO3M6NzoiZHJpYmJsZSI7czowOiIiO3M6NDoibWFpbCI7czoyMjoiaW5mb0BwcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6MjcxOiI8Yj5Mb3JlbSBpcHN1bTwvYj4gZG9sb3Igc2l0IGFtZXQgZGFzIGNvbnNlIA0KbmliaCBldWlzbW9kb3MgdGluY2lkdW50IHV0IGxhb3JlZSBjb25zZQ0KZXN0IGF0LiBOdWxsYSB2aXRhZSA8Yj5lbGl0IGxpYmVybzwvYj4sIGEgcGhhIHNpdCBhbQ0KdGV0dWVyIGFkaXBpc2NpbmcgZWxpdC4gTnVsbGEgdml0YWUgZWxpdCBsZXJvLCANCmEgcGhhcmV0cmEuIDxiPkxvcmVtIGlwc3VtPC9iPiBjdGV0dWVyIGFkaXBpc2NpbmcuIA0KTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQuIjt9aTo2O2E6MTE6e3M6NToib3JkZXIiO3M6MToiNiI7czo1OiJ0aXRsZSI7czo4OiJBbm55IERvZSI7czo0OiJyb2xlIjtzOjE2OiJDdXN0b21lciBTZXJ2aWNlIjtzOjM6InVybCI7czo3NDoiaHR0cDovL21lcmNvci5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS90ZWFtTWVtYmVyNi5wbmciO3M6NDoiaWNvbiI7czo4MDoiaHR0cDovL21lcmNvci5wcmVtaXVtY29kaW5nLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxMi8wOS9zdXBwb3J0VGVhbUljb24tMS5wbmciO3M6NzoidHdpdHRlciI7czozMjoiaHR0cDovL3R3aXR0ZXIuY29tL3ByZW1pdW1jb2RpbmciO3M6ODoiZmFjZWJvb2siO3M6MzY6Imh0dHA6Ly93d3cuZmFjZWJvb2suY29tL0dGbGFzaERlc2lnbiI7czo1OiJ2aW1lbyI7czoxNjoiaHR0cDovL3ZpbWVvLmNvbSI7czo3OiJkcmliYmxlIjtzOjI3OiJodHRwOi8vZHJpYmJibGUuY29tL2dsaml2ZWMiO3M6NDoibWFpbCI7czoyMjoiaW5mb0BwcmVtaXVtY29kaW5nLmNvbSI7czoxMToiZGVzY3JpcHRpb24iO3M6MjcxOiI8Yj5Mb3JlbSBpcHN1bTwvYj4gZG9sb3Igc2l0IGFtZXQgZGFzIGNvbnNlIA0KbmliaCBldWlzbW9kb3MgdGluY2lkdW50IHV0IGxhb3JlZSBjb25zZQ0KZXN0IGF0LiBOdWxsYSB2aXRhZSA8Yj5lbGl0IGxpYmVybzwvYj4sIGEgcGhhIHNpdCBhbQ0KdGV0dWVyIGFkaXBpc2NpbmcgZWxpdC4gTnVsbGEgdml0YWUgZWxpdCBsZXJvLCANCmEgcGhhcmV0cmEuIDxiPkxvcmVtIGlwc3VtPC9iPiBjdGV0dWVyIGFkaXBpc2NpbmcuIA0KTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQuIjt9fXM6MTE6InBvcnRfbnVtYmVyIjtzOjI6IjEyIjtzOjE4OiJzb3J0aW5ncG9zdF9udW1iZXIiO3M6MjoiMTIiO3M6MTM6ImZhY2Vib29rX3Nob3ciO3M6MToiMSI7czo4OiJmYWNlYm9vayI7czozNjoiaHR0cDovL3d3dy5mYWNlYm9vay5jb20vR0ZsYXNoRGVzaWduIjtzOjEyOiJ0d2l0dGVyX3Nob3ciO3M6MToiMSI7czo3OiJ0d2l0dGVyIjtzOjMzOiJodHRwczovL3R3aXR0ZXIuY29tL3ByZW1pdW1jb2RpbmciO3M6MTA6InZpbWVvX3Nob3ciO3M6MToiMSI7czo1OiJ2aW1lbyI7czoxNjoiaHR0cDovL3ZpbWVvLmNvbSI7czoxMjoieW91dHViZV9zaG93IjtzOjE6IjEiO3M6NzoieW91dHViZSI7czoyNzoiaHR0cDovL2RyaWJiYmxlLmNvbS9nbGppdmVjIjtzOjEyOiJzdHVtYmxlX3Nob3ciO3M6MToiMSI7czo3OiJzdHVtYmxlIjtzOjI3OiJodHRwOi8vd3d3LnN0dW1ibGV1cG9uLmNvbS8iO3M6OToiZGlnZ19zaG93IjtzOjE6IjEiO3M6NDoiZGlnZyI7czoxOToiaHR0cDovL3d3dy5kaWdnLmNvbSI7czoxMDoiZW1haWxfc2hvdyI7czoxOiIxIjtzOjU6ImVtYWlsIjtzOjIyOiJpbmZvQHByZW1pdW1jb2RpbmcuY29tIjtzOjEyOiJjb250YWN0ZW1haWwiO3M6MTc6ImluZm9AeW91cm1haWwuY29tIjtzOjEyOiJjb250YWN0ZXJyb3IiO3M6MjU6IkVycm9yIHdoaWxlIHNlbmRpbmcgbWFpbC4iO3M6MTQ6ImNvbnRhY3RzdWNjZXNzIjtzOjc6IlN1Y2Nlc3MiO3M6MTQ6ImVycm9ycGFnZXRpdGxlIjtzOjEwOiJPT09QUyEgNDA0IjtzOjE3OiJlcnJvcnBhZ2VzdWJ0aXRsZSI7czo2NToiU2VlbXMgbGlrZSB5b3Ugc3R1bWJsZWQgYXQgc29tZXRoaW5nIHRoYXQgZG9lc25cXFwndCByZWFsbHkgZXhpc3QiO3M6OToiZXJyb3JwYWdlIjtzOjE3MToiU29ycnksIGJ1dCB0aGUgcGFnZSB5b3UgYXJlIGxvb2tpbmcgZm9yIGhhcyBub3QgYmVlbiBmb3VuZC48YnIvPlRyeSBjaGVja2luZyB0aGUgVVJMIGZvciBlcnJvcnMsIHRoZW4gaGl0IHJlZnJlc2guPC9icj5PciB5b3UgY2FuIHNpbXBseSBjbGljayB0aGUgaWNvbiBiZWxvdyBhbmQgZ28gaG9tZTopIjtzOjE2OiJzaG93c29jaWFsZm9vdGVyIjtzOjE6IjEiO3M6OToiY29weXJpZ2h0IjtzOjU0OiLCqSAyMDEzIGNvcHlyaWdodCBQUkVNSVVNQ09ESU5HIC8vIEFsbCByaWdodHMgcmVzZXJ2ZWQiO3M6MjM6InRyYW5zbGF0aW9uX3NvY2lhbHRpdGxlIjtzOjE3OiJTb2NpYWxpemUgd2l0aCB1cyI7czoyMDoidHJhbnNsYXRpb25fZmFjZWJvb2siO3M6ODoiRmFjZWJvb2siO3M6MTk6InRyYW5zbGF0aW9uX3R3aXR0ZXIiO3M6NzoiVHdpdHRlciI7czoxNzoidHJhbnNsYXRpb25fdmltZW8iO3M6NToiVmltZW8iO3M6MTk6InRyYW5zbGF0aW9uX2RyaWJibGUiO3M6NzoiRHJpYmJsZSI7czoxNzoidHJhbnNsYXRpb25fZW1haWwiO3M6MTM6IlNlbmQgdXMgRW1haWwiO3M6MTY6InRyYW5zbGF0aW9uX3Bvc3QiO3M6MTY6Ik91ciBsYXRlc3QgcG9zdHMiO3M6MjQ6InRyYW5zbGF0aW9uX2VudGVyX3NlYXJjaCI7czoxNToiRW50ZXIgc2VhcmNoLi4uIjtzOjE2OiJ0cmFuc2xhdGlvbl9wb3J0IjtzOjE2OiJSZWNlbnQgcG9ydGZvbGlvIjtzOjIzOiJ0cmFuc2xhdGlvbl9yZWxhdGVkcG9zdCI7czo3OiJSZWxhdGVkIjtzOjI3OiJ0cmFuc2xhdGlvbl9hZHZlcnRpc2VfdGl0bGUiO3M6Mjg6Ik91ciBNb3N0IFJlbm93bmVkIFBlcmZvcm1lcnMiO3M6MjA6InRyYW5zbGF0aW9uX21vcmVsaW5rIjtzOjk6IlJlYWQgbW9yZSI7czoyNDoicG9ydF9wcm9qZWN0X2Rlc2NyaXB0aW9uIjtzOjIwOiJQcm9qZWN0IERlc2NyaXB0aW9uOiI7czoyMDoicG9ydF9wcm9qZWN0X2RldGFpbHMiO3M6MTY6IlByb2plY3QgZGV0YWlsczoiO3M6MTY6InBvcnRfcHJvamVjdF91cmwiO3M6MTI6IlByb2plY3QgVVJMOiI7czoyMToicG9ydF9wcm9qZWN0X2Rlc2lnbmVyIjtzOjE3OiJQcm9qZWN0IGRlc2lnbmVyOiI7czoxNzoicG9ydF9wcm9qZWN0X2RhdGUiO3M6Mjc6IlByb2plY3QgRGF0ZSBvZiBjb21wbGV0aW9uOiI7czoxOToicG9ydF9wcm9qZWN0X2NsaWVudCI7czoxNToiUHJvamVjdCBDbGllbnQ6IjtzOjE4OiJwb3J0X3Byb2plY3Rfc2hhcmUiO3M6MTc6IlNoYXJlIHRoZSBwcm9qZWN0IjtzOjIwOiJwb3J0X3Byb2plY3RfcmVsYXRlZCI7czoxNToiUmVsYXRlZCBwcm9qZWN0IjtzOjE1OiJ0cmFuc2xhdGlvbl9hbGwiO3M6ODoiU2hvdyBhbGwiO3M6MjQ6InRyYW5zbGF0aW9uX25leHRfcHJvamVjdCI7czoxNjoiTmV4dCBwcm9qZWN0IOKGkiI7czoyNzoidHJhbnNsYXRpb25fcHJldml1c19wcm9qZWN0IjtzOjE3OiLihpAgUHJldiBwcm9qZWN0ICI7czoxNDoidHJhbnNsYXRpb25fYnkiO3M6MzoiQnk6IjtzOjIyOiJ0cmFuc2xhdGlvbl9jYXRlZ29yaWVzIjtzOjExOiJDYXRlZ29yaWVzOiI7czoxNjoidHJhbnNsYXRpb25fdGFncyI7czo2OiJUYWdzOiAiO3M6MjY6InRyYW5zbGF0aW9uX3NoYXJlX2NhdGVnb3J5IjtzOjU6IlNoYXJlIjtzOjIxOiJ0cmFuc2xhdGlvbl9ibG9nX3BhZ2UiO3M6NTk6IldlbGNvbWUgdG8gPHNwYW4+b3VyIGJsb2c8L3NwYW4+LCB3ZSB3aWxsIGtlZXAgeW91IGluZm9ybWVkIjtzOjMyOiJ0cmFuc2xhdGlvbl9jb21tZW50X2xlYXZlX3JlcGxheSI7czo1OiJSZXBseSI7czozNToidHJhbnNsYXRpb25fY29tbWVudF9sZWF2ZV9yZXBsYXlfdG8iO3M6MTY6IkxlYXZlIGEgUmVwbHkgdG8iO3M6Mzk6InRyYW5zbGF0aW9uX2NvbW1lbnRfbGVhdmVfcmVwbGF5X2NhbmNsZSI7czoxMzoiQ2FuY2xlIFJlcGxheSI7czoyNDoidHJhbnNsYXRpb25fY29tbWVudF9uYW1lIjtzOjQ6Ik5hbWUiO3M6MjQ6InRyYW5zbGF0aW9uX2NvbW1lbnRfbWFpbCI7czo0OiJNYWlsIjtzOjI3OiJ0cmFuc2xhdGlvbl9jb21tZW50X3dlYnNpdGUiO3M6NzoiV2Vic2l0ZSI7czoyODoidHJhbnNsYXRpb25fY29tbWVudF9yZXF1aXJlZCI7czo4OiJyZXF1aXJlZCI7czoyNjoidHJhbnNsYXRpb25fY29tbWVudF9jbG9zZWQiO3M6MjA6IkNvbW1lbnRzIGFyZSBjbG9zZWQuIjtzOjMxOiJ0cmFuc2xhdGlvbl9jb21tZW50X25vX3Jlc3BvbmNlIjtzOjEwOiJObyBSZXBsaWVzIjtzOjMxOiJ0cmFuc2xhdGlvbl9jb21tZW50X29uZV9jb21tZW50IjtzOjk6Ik9uZSBSZXBseSI7czozMToidHJhbnNsYXRpb25fY29tbWVudF9tYXhfY29tbWVudCI7czo3OiJSZXBsaWVzIjtzOjI0OiJ0cmFuc2xhdGlvbl9jb250YWN0X25hbWUiO3M6NDoiTmFtZSI7czoyNToidHJhbnNsYXRpb25fY29udGFjdF9lbWFpbCI7czo1OiJFbWFpbCI7czoyNzoidHJhbnNsYXRpb25fY29udGFjdF9tZXNzYWdlIjtzOjc6Ik1lc3NhZ2UiO3M6MjQ6InRyYW5zbGF0aW9uX2NvbnRhY3Rfc2VuZCI7czoxMjoiU2VuZCBNZXNzYWdlIjtzOjI1OiJ0cmFuc2xhdGlvbl9jb250YWN0X2NsZWFyIjtzOjU6IkNsZWFyIjt9';
     	$data = unserialize(base64_decode($data)); //100% safe - ignore theme check nag
		update_option('of_options', $data);

	}
	//delete_option(OPTIONS);

}

// Build Options
require_once (ADMIN_PATH . 'theme-options.php'); 		// Options panel settings and custom settings
require_once (ADMIN_PATH . 'admin-interface.php');		// Admin Interfaces
require_once (ADMIN_PATH . 'admin-functions.php'); 	// Theme actions based on options settings
require_once (ADMIN_PATH . 'medialibrary-uploader.php'); // Media Library Uploader


$includes =  get_template_directory() . '/includes/';
$widget_includes =  get_template_directory() . '/includes/widgets/';

require_once ($includes  . 'scripts.php'); // Load JS

// Other theme options
require_once ($includes . 'menu.php'); 		   // Menus
require_once ($includes . 'sidebars.php');
require_once ($includes . 'shortcodes.php');

require_once ($widget_includes . 'pop_widget.php');
require_once ($widget_includes . 'racent_widget.php');
require_once ($widget_includes . 'contact_widget.php');







if (function_exists('icl_object_id')) {
    function languages_list_footer(){
    $languages = icl_get_languages('skip_missing=0&orderby=code');
    if(!empty($languages)){
        echo '<div id="footer_language_list"><ul>';
        foreach($languages as $l){
            echo '<li>';
            if($l['country_flag_url']){
                if(!$l['active']) echo '<a href="'.$l['url'].'">';
                echo '<img src="'.$l['country_flag_url'].'" height="12" alt="'.$l['language_code'].'" width="18" />';
                if(!$l['active']) echo '</a>';
            }

            echo '</li>';
        }
        echo '</ul></div>';
    }
	}
	function current_language(){

		global $sitepress;

		$current_language = $sitepress->get_current_language();

		return $current_language;

	}
}

	function showTopCart() {

		global $data, $sitepress;
		?>
		<div class="cartHolder">
			<div class="top-nav">
				<div class="socialTop">
					<?php socialLinkTop() ?>
					<?php if (function_exists('icl_object_id')) { echo languages_list_footer(); } ?>
				</div>
				<ul>
					<?php
					if ( has_nav_menu( 'top_menu' ) ) {
						wp_nav_menu( array('theme_location' => 'top_menu', 'container' => 'false', 'menu_class' => 'top-nav', 'echo' => true, 'items_wrap' => '%3$s' ));
					}
					?>
				</ul>
			</div>
		</div>
		<?php
	}




function fl_shortcode_button() {
	if ( ! current_user_can('edit_posts') && ! current_user_can('edit_pages') )
		return;

	// Add only in Rich Editor mode
	if ( get_user_option('rich_editing') == 'true') {
		add_filter("mce_external_plugins", "fl_add_shortcode_tinymce_plugin");
		add_filter('mce_buttons', 'fl_register_shortcode_button');
	}
}


 if ( ! isset( $content_width ) ) $content_width = 960;
/**
 * Register the TinyMCE Shortcode Button
 */
function fl_register_shortcode_button($buttons) {
	array_push($buttons, "|", "flshortcodes");
	return $buttons;
}

/**
 * Load the TinyMCE plugin: shortcode_plugin.js
 */
function fl_add_shortcode_tinymce_plugin($plugin_array) {
   $plugin_array['flshortcodes'] = get_template_directory_uri() . '/js/shortcode_plugin.js';
   return $plugin_array;
}



function shortcontent($start, $end, $new, $source, $lenght){
$text = strip_tags(preg_replace('/<h(.*)>(.*)<\/h(.*)>.*/iU', '', $source), '<b><strong>');
$text = preg_replace('#\[video\](.*)\[\/video\]#si', '', $text);
$text = preg_replace('#\[pmc_link\](.*)\[\/pmc_link\]#si', '', $text);
$text = preg_replace('/\[[^\]]*\]/', $new, $text);
return substr(preg_replace('/\s[\s]+/','',$text),0,$lenght);

}

function fl_refresh_mce($ver) {
  $ver += 3;
  return $ver;
}

function the_breadcrumb() {
	if (!is_home()) {
		echo '<a href="';
		echo home_url();
		echo '">';
		bloginfo('name');
		echo "</a> » ";
		if (is_single()) {
			if (is_single()) {
				the_title();
			}
		} elseif (is_page()) {
			echo the_title();
		}
		elseif(get_query_var('portfoliocategory')){
			$cat = get_query_var('portfoliocategory');
			$cat = str_replace('-',' ',$cat);
			echo $cat;
		}
		else if(get_query_var('tag')){
			$tag = get_query_var('tag');
			$tag = str_replace('-',' ',$tag);
			echo $tag;
		}
		else if(get_query_var('s')){
			the_search_query();
		}
		else if(get_query_var('cat')){
			$cat = get_query_var('cat');
			$cat = get_category($cat);
			echo $cat->name;
		}
		else if(get_query_var('m')){
			echo __('Archive','wp-rockPalace');
		}
		else{
			echo 'Home';
		}
	}
}

function social($url) {
	$social = '';
	global $data;
	$social .= '<div id="social">';
	if($data['facebook_show'] == 1)
	$social .= '<div class="fb-like" data-href="'.$url.'" data-send="false" data-width="80" data-layout="button_count" data-show-faces="false"></div>';
	if($data['twitter_show'] == 1)
	$social .= '<div id="twitter"><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="'.$name.'">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>';
	if($data['google_show'] == 1)
	$social .= '<div class="g-plusone" data-size="medium"></div>';
	$social .=	'</div>';

	echo $social;
}




function footer(){
	function pmc_recent_footer_excerpt_length( $length ) {
		return 40;
	}

	function pmc_recent_footer_title($title) { return  substr($title, 0, 40). '';}

	add_filter( 'excerpt_length', 'pmc_recent_footer_excerpt_length', 999 );
	add_filter('the_title', 'pmc_recent_footer_title') ;
}

function shortTitle($lenght)
{
	$title = the_title('','',FALSE);
	echo substr($title, 0, $lenght);
}
function custom_excerpt_length( $length ) {
	return 30;
}
add_filter( 'excerpt_length', 'custom_excerpt_length', 999 );
function new_excerpt_more($more) {
	return '';
}
add_filter('excerpt_more', 'new_excerpt_more');



function socialLinkProduct() {
	$social = '';
	$social ='<div class="addthis_toolbox"><div class="custom_images">';
	global $data;
	if($data['facebook_show'] == 1)
	$social .= '<a class="addthis_button_facebook" title="'.translation('translation_facebook', 'Facebook').'"><img src="'. get_template_directory_uri() .'/images/icon-facebook-product-single.png" width="16" height="16"  alt="'.translation('translation_facebook', 'Facebook').'" /></a>';
	if($data['twitter_show'] == 1)
	$social .= '<a class="addthis_button_twitter" title="'.translation('translation_twitter', 'Twitter').'"><img src="'. get_template_directory_uri() .'/images/icon-twitter-product-single.png" width="16" height="16"  alt="'.translation('translation_twitter', 'Twitter').'" /></a>';
	$social .='<a class="addthis_button_more"><img src="'. get_template_directory_uri() .'/images/icon-more-product-single.png" width="16" height="16"  alt="More..." /></a></div><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f3049381724ac5b"></script>';
	if($data['email_show'] == 1)
	$social .= '<a class="emaillink" href="mailto:'.$data['email'].'" title="'.translation('translation_email', 'Send us Email').'"></a></div>';
	echo $social;
}

function socialLinkTop() {
	$social = '';
	global $data;
	if($data['facebook_show'] == 1)
	$social .= '<a target="_blank" class="facebooklink top" href="'.$data['facebook'].'" title="'.translation('translation_facebook', 'Facebook').'"></a>';
	if($data['youtube_show'] == 1)
	$social .= '<a target="_blank" class="dribble top" href="'.$data['youtube'].'" title="'.translation('translation_dribble', 'Dribble').'"></a>';
	if($data['twitter_show'] == 1)
	$social .= '<a target="_blank" class="twitterlink top" href="'.$data['twitter'].'" title="'.translation('translation_twitter', 'Twitter').'"></a>';
	if($data['email_show'] == 1)
	$social .= '<a target="_blank" class="emaillink top" href="mailto:'.$data['email'].'" title="'.translation('translation_email', 'Send us Email').'"></a>';
	if($data['digg_show'] == 1)
	$social .= '<a target="_blank" class="vimeo top" href="'.$data['digg'].'" title="'.translation('translation_vimeo', 'Vimeo').'"></a>';


	echo $social;
}

function socialLinkTeam($facebook,$twitter,$vimeo,$dribble,$email) {
	$social = '';
	global $data;
	if($facebook != '')
	$social .= '<a target="_blank" class="facebooklink" href="'.$facebook.'" title="'.translation('translation_facebook', 'Facebook').'"></a>';
	if($twitter != '')
	$social .= '<a target="_blank" class="twitterlink" href="'.$twitter.'" title="'.translation('translation_twitter', 'Twitter').'"></a>';
	if($vimeo != '')
	$social .= '<a target="_blank" class="vimeo" href="'.$vimeo.'" title="'.translation('translation_vimeo', 'Vimeo').'"></a>';
	if($dribble != '')
	$social .= '<a target="_blank" class="dribble" href="'.$dribble.'" title="'.translation('translation_dribble', 'Dribble').'"></a>';
	if($email != '')
	$social .= '<a target="_blank" class="emaillink" href="mailto:'.$email.'" title="'.translation('translation_email', 'Send us Email').'"></a>';
	echo $social;
}


function socialLinkCat($link,$title,$email) {
	global $data,$sitepress;;
	$social = '';
	$social .='<a class="addthis_button" addthis:url="'.$link.'" addthis:title="'.$title.'" ><img src="'. get_template_directory_uri() .'/images/socialIconShareMore.png" width="64" height="64"  alt="More..." />';
	$social .= translation('translation_share_category', 'Share');
	$social .='</a><script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-507800a118eab6fa"></script>';

	echo $social; }



function socialLinkSingle() {
	$social = '';
	$social ='<div class="addthis_toolbox"><div class="custom_images">';
	global $data;
	if($data['facebook_show'] == 1)
	$social .= '<a class="addthis_button_facebook" title="'.translation('translation_facebook', 'Facebook').'"><img src="'. get_template_directory_uri() .'/images/facebookPortfolioIcon.png" width="64" height="64"  alt="'.translation('translation_facebook', 'Facebook').'" /></a>';
	if($data['twitter_show'] == 1)
	$social .= '<a class="addthis_button_twitter" title="'.translation('translation_twitter', 'Twitter').'"><img src="'. get_template_directory_uri() .'/images/twitterPortfolioIcon.png" width="64" height="64"  alt="'.translation('translation_twitter', 'Twitter').'" /></a>';
	if($data['digg_show'] == 1)
	$social .= '<a class="addthis_button_digg" title="'.translation('translation_vimeo', 'Vimeo').'"><img src="'. get_template_directory_uri() .'/images/diggPortfolioIcon.png" width="64" height="64"  alt="'.translation('translation_vimeo', 'Vimeo').'" /></a>';
	$social .='<a class="addthis_button_more"><img src="'. get_template_directory_uri() .'/images/addPortfolioIcon.png" width="64" height="64"  alt="More..." /></a></div><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f3049381724ac5b"></script>';
	if($data['email_show'] == 1)
	$social .= '<a class="emaillink" href="mailto:'.$data['email'].'" title="'.translation('translation_email', 'Send us Email').'"><img src="'. get_template_directory_uri() .'/images/emailPortfolioIcon.png" width="24" height="24"  alt="More..." /></a></div>';
	echo $social;
}

function translation($theme_name, $translation_name){
	global $data, $sitepress;
	if (!function_exists('icl_object_id') or (ICL_LANGUAGE_CODE == $sitepress->get_default_language()) ) {
		if(isset($data[$theme_name]))
			$string = stripText($data[$theme_name]);
		else
			$string = '';
		}
	else {
		$string = __($translation_name,'wp-rockPalace');
	}
	return $string;

}

function get_category_id($cat_name){
	$term = get_term_by('name', $cat_name, 'category');
	return $term->term_id;
}
/**
 * Init process for button control
 */
add_filter( 'tiny_mce_version', 'fl_refresh_mce');
add_action( 'init', 'fl_shortcode_button' );


add_filter('the_content', 'addlightboxrel_replace');

function addlightboxrel_replace ($content)
{	global $post;
	$pattern = "/<a(.*?)href=('|\")(.*?).(bmp|gif|jpeg|jpg|png)('|\")(.*?)>/i";
  	$replacement = '<a$1href=$2$3.$4$5 rel="lightbox[%LIGHTID%]"$6>';
    $content = preg_replace($pattern, $replacement, $content);
	if(isset($post->ID))
		$content = str_replace("%LIGHTID%", $post->ID, $content);
    return $content;
}


function filter_content_video( $content ){
	$content = explode('[video]', $content );
	$content = explode('[/video]',$content[1] );
	$content = $content[0];
	return $content;
}

function filter_content( $content ){
	$content = explode('[video]', $content );
	$contentpost = $content[0] . '';
	$content = explode('[/video]',$content[1] );
	$contentpost .= $content[1];
	return $contentpost;
}

function filter_link( $content ){
	$content = explode('[pmc_link]', $content );
	$content = explode('[/pmc_link]',$content[1] );
	$content = $content[0];
	return $content;
}

function filter_content_link( $content ){
	$content = explode('[pmc_link]', $content );
	$contentcat = $content[0];
	$content = explode('[/pmc_link]',$content[1] );
	$contentcat .= $content[1];
	return $contentcat;
}

function filter_content_gallery( $content ){
	$content = explode('[gallery]', $content );
	$contentgal = $content[0];
	return $contentgal;
}



function stripText($string)
{
    return str_replace("\\",'',$string);
}



/*portfolio loop*/

function portfolio($portSize, $item, $post = 'port' ,$number = 0,$cat = ''){
	global $data;
	$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
	$categport = '';

	if($post == 'post'){
		$postT = 'post';
		$showposts = $data['sortingpost_number'];
		$postC = 'category';
		$categport="";
		}
	else{
		$postT = 'portfolioentry';
		$postC = 'portfoliocategory';
		$showposts = $data['port_number'];
		if($cat != '')
			$categport='&portfoliocategory='.$cat;
		}

	if($number != 0)
		$showposts = $number;

	$postPage = '&posts_per_page='.$showposts;

	if($item == 3){
		$titleChar = 999;
	}
	else if($item == 2){
		$titleChar = 25;
	}
	else {
		$titleChar = 25;
	}


	if($categport != "")
		$pmc = new WP_Query(array('orderby=date', 'post_type' =>  $postT, 'paged' => $paged, 'post_status' => 'publish', 'ignore_sticky_posts' => 1, 'posts_per_page' => $showposts ,'portfoliocategory' => $cat ));
	else
		$pmc = new WP_Query(array('orderby=date', 'post_type' =>  $postT, 'post_status' => 'publish', 'ignore_sticky_posts' => 1, 'posts_per_page' => $showposts , 'paged' => $paged,'suppress_filters' => false));


	$limit_text = 100;
	$currentindex = '';
	$counter = 0;
	$portfolio = '';
	$count = 0;
	while ( $pmc->have_posts() ) : $pmc->the_post();
		$do_not_duplicate = get_the_ID();
		$full_image = wp_get_attachment_image_src(get_post_thumbnail_id(), $portSize, false);
		$entrycategory = get_the_term_list( get_the_ID(), $postC, '', ' ', '' );
		$catstring = $entrycategory;
		$catstring = strip_tags($catstring);
		$catidlist = explode(" ", $catstring);
		for($i = 0; $i < sizeof($catidlist); ++$i){
			$catidlist[$i].=$currentindex;
		}
		$catlist = implode(" ", $catidlist);
    $catlist = str_replace(' ', '-', $catlist);

		$counter++;
		$category = get_the_term_list( get_the_ID(), $postC, '', ', ', '' );
		if ( has_post_format( 'link' , get_the_ID()))
			$linkPost = filter_link(get_the_content());
		else
			if (function_exists('icl_object_id'))
				$linkPost = get_permalink(icl_object_id(get_the_ID(), 'portfolioentry', true, true));
			else
				$linkPost = get_permalink();


		if($item != 2){

		$portfolio .= '<div class="item'.$item.' '.$catlist .'" data-category="'. $catlist.'">';
			if($item != 3) {
				$portfolio .= '
				<div class="overdefult">
					<a href="'. $linkPost .'">
						<div class="portDate">'.  get_the_date() .'</div>
						<div class="portIcon"></div>
						<div class="portCategory">'. $category .'</div>
					</a>
				</div>
			<div class="image">
				<div class="loading"></div>
				<img src="'. $full_image[0] .'">
			</div>';}
			if($item == 3) {

			$portfolio .= '
				<div class="recentimage">
					<div class="overdefult">
							<a class="overdefultlink" href="'. $linkPost .'">
								<div class="portDate">'. get_the_date() .'</div>
								<div class="portIcon"></div>
								<div class="portCategory">'. $category .'</div>
							</a>
					</div>
					<div class="image">
						<div class="loading"></div>
						<img src="'. $full_image[0] .'">
					</div>
				</div>';
			}


			if($item != 3)
				$portfolio .= '<h4><a href="'. $linkPost .'">'. substr(the_title('','',FALSE),0,$titleChar)  .'</a></h4>';
			if($item == 3) {
				$portfolio .= '<div class="recentdescription">
					<h3><a class="overdefultlink" href="'. $linkPost .'">'.  substr(the_title('','',FALSE),0,$titleChar)  .'</a></h3>

					<div class="descriptionHomePort">
						<div class="borderLine"><div class="borderLineLeft"></div><div class="borderLineRight"></div></div>
						<div>'. shortcontent("[", "]", "", get_the_content() ,145) .'...'.closeTagsReturn(shortcontent("[", "]", "", get_the_content() ,145)).'</div>
					</div>
				</div>';
			}


		$portfolio .= '</div>';

		} else {
		$category = get_the_term_list( get_the_ID(), $postC, '', '', '' );
		$categoryHover = get_the_term_list( get_the_ID(), $postC, '', ', ', '' );
		if($count != 2){
			$portfolio .= '<div class="one_half item2 '.$catlist .'" data-category="'. $catlist.'" >';
		}
		else{
			$portfolio .= '<div class="one_half last item2 '.$catlist .'" data-category="'. $catlist.'" >';
			$count = 0;
		}

			$portfolio .= '	<div class="recentimage">
					<div class="overdefult">
						<a href="'. $linkPost .'">
							<div class="portDate">'. get_the_date() .'</div>
							<div class="portIcon"></div>
							<div class="portCategory">'. $categoryHover  .'</div>
						</a>
					</div>

					<div class="image">
						<div class="loading"></div>
						<img src="'. $full_image[0] .'">
					</div>
				</div>
				<div class="recentdescription">
					<h3><a class="overdefultlink" href="'.$linkPost.'">'. substr(the_title('','',FALSE),0,99999) .'</a></h3>
					<h3 class="category">'. $category .'</h3>
					<div class="description">'. shortcontent("[", "]", "", get_the_content() ,125) .'...'.closeTagsReturn(shortcontent("[", "]", "", get_the_content() ,125)).'</div>
				</div>
			</div>';

		$count++;

		}



	endwhile;

	echo $portfolio;
}

add_action('init', 'create_portfolio');

function create_portfolio() {
	$portfolio_args = array(
		'label' => 'Portfolio',
		'singular_label' => 'Portfolio',
		'public' => true,
		'show_ui' => true,
		'capability_type' => 'post',
		'hierarchical' => false,
		'rewrite' => true,
		'supports' => array('title', 'editor', 'thumbnail', 'author', 'comments', 'excerpt')
	);
	register_post_type('portfolioentry',$portfolio_args);
}
add_action("admin_init", "add_portfolio");
add_action('save_post', 'update_portfolio_data');

function add_portfolio(){
	add_meta_box("portfolio_details", "Portfolio Entry Options", "portfolio_options", "portfolioentry", "normal", "high");
}

function update_portfolio_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["author"]) ) {
			update_post_meta($post->ID, "author", $_POST["author"]);
		}
		if( isset($_POST["date"]) ) {
			update_post_meta($post->ID, "date", $_POST["date"]);
		}
		if( isset($_POST["detail_active"]) ) {
			update_post_meta($post->ID, "detail_active", $_POST["detail_active"]);
		}else{
			update_post_meta($post->ID, "detail_active", 0);
		}
		if( isset($_POST["website_url"]) ) {
			update_post_meta($post->ID, "website_url", $_POST["website_url"]);
		}
		if( isset($_POST["status"]) ) {
			update_post_meta($post->ID, "status", $_POST["status"]);
		}
		if( isset($_POST["customer"]) ) {
			update_post_meta($post->ID, "customer", $_POST["customer"]);
		}

	}
}

function portfolio_options(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["author"][0])){
		$author = $data["author"][0];
	}else{
		$author = "";
	}
	if (isset($data["date"][0])){
		$date = $data["date"][0];
	}else{
		$date = "";
	}
	if (isset($data["status"][0])){
		$status = $data["status"][0];
	}else{
		$status = "";
	}
	if (isset($data["detail_active"][0])){
		$detail_active = $data["detail_active"][0];
	}else{
		$detail_active = 0;
		$data["detail_active"][0] = 0;
	}
	if (isset($data["website_url"][0])){
		$website_url = $data["website_url"][0];
	}else{
		$website_url = "";
	}

	if (isset($data["customer"][0])){
		$customer = $data["customer"][0];
	}else{
		$customer = "";
	}	 ?>
    <div id="portfolio-options">
        <table cellpadding="15" cellspacing="15">
        	<tr>
                <td colspan="2"><strong>Portfolio Overview Options:</strong></td>
            </tr>
            <tr>
                <td><label>Link to Detail Page: <i style="color: #999999;">(Do you want a project detail page?)</i></label></td><td><input type="checkbox" name="detail_active" value="1" <?php if( isset($detail_active)){ checked( '1', $data["detail_active"][0] ); } ?> /></td>
            </tr>
            <tr>
            	<td><label>Project Link: <i style="color: #999999;">(The URL of your project)</i></label></td><td><input name="website_url" style="width:500px" value="<?php echo $website_url; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Project Author: <i style="color: #999999;">(The URL of your project)</i></label></td><td><input name="author" style="width:500px" value="<?php echo $author; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Project date: <i style="color: #999999;">(Date of project)</i></label></td><td><input name="date" style="width:500px" value="<?php echo $date; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Customer: <i style="color: #999999;">(Customer of project)</i></label></td><td><input name="customer" style="width:500px" value="<?php echo $customer; ?>" /></td>
            </tr>
            <tr>
            	<td><label>Project status: <i style="color: #999999;">(Status of project)</i></label></td><td><input name="status" style="width:500px" value="<?php echo $status; ?>" /></td>
            </tr>
        </table>
    </div>

<?php
}

function add_portfolio_category(){
	add_meta_box("portfolio_categories", "Portfolio categories(only for portfolio templates)", "portfolio_category_options", "page", "normal", "high");
}

add_action('save_post', 'update_portfolio_category_data');
add_action("admin_init", "add_portfolio_category");

function portfolio_category_options(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["port_category"][0])){
		$port_category = $data["port_category"][0];
	}else{
		$port_category = "";
	}

?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">
        	<tr>
                <td colspan="2"><strong>Portfolio category(only for portfolio templates):</strong></td>
            </tr>
            <tr>
            	<td><label>Category: <i style="color: #999999;">(select category)</i></label></td><td>
				<?php wp_dropdown_categories('show_option_all=Show all&hierarchical=2&name=port_category&taxonomy=portfoliocategory&selected='.$port_category.''); ?>
				</td>
            </tr>

        </table>
    </div>

<?php
}
function update_portfolio_category_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["port_category"]) ) {
			update_post_meta($post->ID, "port_category", $_POST["port_category"]);
		}

	}
}


register_taxonomy("portfoliocategory", array("portfolioentry"), array("hierarchical" => true, "label" => "Portfolio Categories", "singular_label" => "Portfolio Category", "rewrite" => true));

function getcatslug($catID){
		$cat_obj = get_term($catID, 'portfoliocategory');
		$cat_slug = '';
		$cat_slug = $cat_obj->slug;
		return $cat_slug;
	}

function add_slider_category(){
	add_meta_box("slider_categories", "Post type", "slider_category_options_post", "post", "normal", "high");

}


add_action('save_post', 'update_slider_category_data');
add_action("admin_init", "add_slider_category");


function slider_category_options_post(){
	global $post;
	$data = get_post_custom($post->ID);
	if (isset($data["slider_category"][0])){
		$slider_category = $data["slider_category"][0];
	}else{
		$slider_category = "";
	}
	if (isset($data["video_post_url"][0])){
		$video_post_url = $data["video_post_url"][0];
	}else{
		$video_post_url = "";
	}
	if (isset($data["video_active_post"][0])){
		$video_active_post = $data["video_active_post"][0];
	}else{
		$video_active_post = 0;
		$data["video_active_post"][0] = 0;
	}

	if (isset($data["link_post_url"][0])){
		$link_post_url = $data["link_post_url"][0];
	}else{
		$link_post_url = "";
	}

	if (isset($data["audio_post_url"][0])){
		$audio_post_url = $data["audio_post_url"][0];
	}else{
		$audio_post_url = "";
	}

	if (isset($data["audio_post_title"][0])){
		$audio_post_title = $data["audio_post_title"][0];
	}else{
		$audio_post_title = "";
	}

	if (isset($data["selectv"][0])){
		$selectv = $data["selectv"][0];
	}else{
		$selectv = "";
	}



?>
    <div id="portfolio-category-options">
        <table cellpadding="15" cellspacing="15">

            <tr class="videoonly">
            	<td><label>Video URL(*required): <i style="color: #999999;">
				<br>Link should look for Youtube: http://www.youtube.com/watch?v=WhBoR_tgXCI - So ID is WhBoR_tgXCI
				<br>Link should look for Vimeo: http://vimeo.com/29017795 so ID is 29017795 <br></i></label><br><input name="video_post_url" style="width:500px" value="<?php echo $video_post_url; ?>" /></td>
            </tr>
            <tr class="select_video">
            	<td><label>Select video: <i style="color: #999999;">
				<select name="selectv">
				<?php if ($selectv == 'vimeo') {?>
				  <option value="vimeo" selected>Vimeo</option>
				 <?php } else {?>
				  <option value="vimeo">Vimeo</option>
				 <?php }?>
				<?php if ($selectv == 'youtube') {?>
				  <option value="youtube" selected>YouTube</option>
				 <?php } else {?>
				  <option value="youtube">YouTube</option>
				 <?php }?>
				</select>

            </tr>
            <tr class="linkonly">
            	<td><label>Link URL: <i style="color: #999999;"></i></label><br></td><td><input name="link_post_url" style="width:500px" value="<?php echo $link_post_url; ?>" /></td>
            </tr>

            <tr class="audioonly">
            	<td><label>Audio URL: <i style="color: #999999;"></i></label><br></td><td><input name="audio_post_url" style="width:500px" value="<?php echo $audio_post_url; ?>" /></td>
            </tr>
            <tr class="audioonly">
            	<td><label>Audio title : <i style="color: #999999;"></i></label><br></td><td><input name="audio_post_title" style="width:500px" value="<?php echo $audio_post_title; ?>" /></td>
            </tr>

        </table>
		<script>
		jQuery(document).ready(function(){
				if (jQuery("input[name=post_format]:checked").val() == 'video'){
					jQuery('.videoonly , .select_video').show();
					jQuery('.linkonly').hide();
					jQuery('.audioonly').hide();}

				else if (jQuery("input[name=post_format]:checked").val() == 'link'){
					jQuery('.linkonly').show();
					jQuery('.videoonly, .select_video').hide();
					jQuery('.audioonly').hide();}
				else if (jQuery("input[name=post_format]:checked").val() == 'audio'){
					jQuery('.linkonly').hide();
					jQuery('.videoonly, .select_video').hide();
					jQuery('.audioonly').show();}
				else{
					jQuery('.videoonly').hide();
					jQuery('.audioonly').hide();
					jQuery('.linkonly, .select_video').hide();}

				jQuery("input[name=post_format]").change(function(){
				if (jQuery("input[name=post_format]:checked").val() == 'video'){
					jQuery('.videoonly, .select_video').show();
					jQuery('.linkonly').hide();
					jQuery('.audioonly').hide();}
				else if (jQuery("input[name=post_format]:checked").val() == 'link'){
					jQuery('.linkonly').show();
					jQuery('.videoonly, .select_video').hide();
					jQuery('.audioonly').hide();}
				else if (jQuery("input[name=post_format]:checked").val() == 'audio'){
					jQuery('.linkonly').hide();
					jQuery('.audioonly').show();
					jQuery('.videoonly, .select_video').hide();	}
				else{
					jQuery('.videoonly, .select_video').hide();
					jQuery('.linkonly').hide();
					jQuery('.audioonly').hide();}
			});
		});
		</script>
    </div>


<?php



}


function update_slider_category_data(){
	global $post;
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
        return $post_id;
    }
	if($post){
		if( isset($_POST["slider_category"]) ) {
			update_post_meta($post->ID, "slider_category", $_POST["slider_category"]);
		}
		if( isset($_POST["video_post_url"]) ) {
			update_post_meta($post->ID, "video_post_url", $_POST["video_post_url"]);
		}
		if( isset($_POST["video_active_post"]) ) {
			update_post_meta($post->ID, "video_active_post", $_POST["video_active_post"]);
		}else{
			update_post_meta($post->ID, "video_active_post", 0);
		}
		if( isset($_POST["link_post_url"]) ) {
			update_post_meta($post->ID, "link_post_url", $_POST["link_post_url"]);
		}
		if( isset($_POST["audio_post_url"]) ) {
			update_post_meta($post->ID, "audio_post_url", $_POST["audio_post_url"]);
		}
		if( isset($_POST["audio_post_title"]) ) {
			update_post_meta($post->ID, "audio_post_title", $_POST["audio_post_title"]);
		}
		if( isset($_POST["selectv"]) ) {
			update_post_meta($post->ID, "selectv", $_POST["selectv"]);
		}
	}



}




if( !function_exists( 'ideo_fallback_menu' ) )
{
	/**
	 * Create a navigation out of pages if the user didnt create a menu in the backend
	 *
	 */
	function ideo_fallback_menu()
	{
		$current = "";
		if (is_front_page()){$current = "class='current-menu-item'";}


		echo "<div class='fallback_menu'>";
		echo "<ul class='ideo_fallback menu'>";
		echo "<li $current><a href='".get_bloginfo('url')."'>Home</a></li>";
		wp_list_pages('title_li=&sort_column=menu_order');
		echo "</ul></div>";
	}
}


function removeChar($char){
	$char = explode('#',$char);
	return $char[1];
}

/*audio player*/
function wp_audio_player_head() {
	global $data;

	echo '<script type="text/javascript" src="'.get_template_directory_uri().'/js/audio-player.js"></script>';
	echo '<script type="text/javascript">';
	echo 'AudioPlayer.setup("'.get_template_directory_uri().'/js/player.swf", {';
	echo 'width: 598,animation:"no", bg:"2a2b2c",leftbg:"1e1e20", rightbg:"1e1e20", volslider:"'.removeChar($data['mainColor']).'", voltrack:"ffffff", lefticon:"ffffff",righticon:"ffffff",skip:"ffffff", loader:"'.removeChar($data['mainColor']).'",
		 righticonhover:"ffffff", rightbghover:"'.removeChar($data['mainColor']).'", text:"1e1e20", border:"1e1e20"';
	echo '});</script>';
}
add_action('wp_head','wp_audio_player_head');

function wp_audio_player($atts) {
extract(shortcode_atts(array(
    'no' => '1',
    'file' => 'http://'
  ), $atts));
	$postmeta = get_post_custom(get_the_id());
	$title = 'Sample title';
	if(isset($postmeta["audio_product_title"][0]))
		$title = $postmeta["audio_product_title"][0];
	if(isset($postmeta["audio_post_title"][0]))
		$title = $postmeta["audio_post_title"][0];

	return '<script type="text/javascript">AudioPlayer.embed("audioplayer_$no", {soundFile: "'.$file.'",titles: "'.$title.'"});</script><p id="audioplayer_$no">
			<audio controls="controls">
			<source src="'.$file.'" type="audio/mpeg" />
			Your browser does not support the audio tag.
			</audio>
			</p>';
}
add_shortcode('audio', 'wp_audio_player');

function closeTags($string){
	$output  = '';
	$open = $close = 0;
	$open = substr_count($string , '<strong>');
	$close = substr_count($string , '</strong>');
	if($open > $close )
		$output .='</strong>';
	echo $output;
}

function closeTagsReturn($string){
	$output  = '';
	$open = $close = 0;
	$open = substr_count($string , '<strong>');
	$close = substr_count($string , '</strong>');
	if($open > $close )
		$output .='</strong>';
	return $output;
}

function add_this_script_footer(){
	global $data, $sitepress;

		if (!function_exists('icl_object_id') or (ICL_LANGUAGE_CODE == $sitepress->get_default_language()) ) {
			$search = stripText($data['translation_enter_search']);

			}
		else {
			$search = __('Enter search...','wp-rockPalace');

		}
?>
<script>
	jQuery(document).ready(function(){
		jQuery('#sidebarsearch input').val('<?php echo $search ?>');

		jQuery('#sidebarsearch input').focus(function() {
			jQuery('#sidebarsearch input').val('');
		});

		jQuery('#sidebarsearch input').focusout(function() {
			jQuery('#sidebarsearch input').val('<?php echo $search ?>');
		});

	});



	jQuery("a[rel^='lightbox']").prettyPhoto({theme:'light_rounded',overlay_gallery: false,show_title: false});
</script>
<?php  }


add_action('wp_footer', 'add_this_script_footer');


add_filter( 'the_category', 'add_nofollow_cat' );

function add_nofollow_cat( $text ) {
	$text = str_replace('rel="category tag"', "", $text);
	return $text;
	}

function getImage($image){

	if ( has_post_thumbnail() ){
		the_post_thumbnail($image);
		}
	else
		echo '<img src ="'.get_template_directory_uri() . '/images/placeholder-580.png" alt="'.the_title('','',FALSE).'" >';

}
?>